<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RoleToPermission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class RolesAndPermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // create permissions
        $pers = [
            'dashboard'=>[
                'access-dashboard',
                'dashboard-manage',
            ],
            'user'=>[
                'user-manage',
                'user-add',
                'user-edit',
                'user-delete',
                'user-impersonate',
                'user-access-dashboard',
            ],
            'activity'=>[
                'activity-manage',
                'activity-add',
                'activity-edit',
                'activity-delete'
            ],
            'permission'=>[
                'permission-manage',
                'permission-add',
                'permission-edit',
                'permission-delete',
                'permission-change'
            ],
            'role'=>[
                'role-manage',
                'role-add',
                'role-edit',
                'role-delete',
                'role-change'
            ],
            'backup'=>[
                'backup-manage',
                'backup-delete'
            ],
            'visitor'=>[
                'visitor-manage',
                'visitor-delete'
            ],
            'setting'=>[
                'setting-manage',
                'language-manage',
            ],
            'employee'=>[
                'employee-manage',
                'employee-add',
                'employee-edit',
                'employee-delete'
            ],
            'about'=>[
                'about-edit',
            ],
            'slider'=>[
                'slider-manage',
                'slider-add',
                'slider-edit',
                'slider-delete'
            ],
            'pack-size'=>[
                'pack-size-manage',
                'pack-size-add',
                'pack-size-edit',
                'pack-size-delete'
            ],
            'bank-list'=>[
                'bank-list-manage',
                'bank-list-add',
                'bank-list-edit',
                'bank-list-delete'
            ],
            'employee-category'=>[
                'employee-category-manage',
                'employee-category-add',
                'employee-category-edit',
                'employee-category-delete'
            ],
            'product-category'=>[
                'product-category-manage',
                'product-category-add',
                'product-category-edit',
                'product-category-delete'
            ],
            'license-category'=>[
                'license-category-manage',
                'license-category-add',
                'license-category-edit',
                'license-category-delete'
            ],
            'product-license'=>[
                'product-license-manage',
                'product-license-add',
                'product-license-show',
                'product-license-edit',
                'product-license-delete'
            ],
            'user-bank-accounts'=>[
                'user-bank-accounts-manage',
                'user-bank-accounts-add',
                'user-bank-accounts-edit',
                'user-bank-accounts-delete'
            ],
            'office-expense-category'=>[
                'office-expense-category-manage',
                'office-expense-category-add',
                'office-expense-category-edit',
                'office-expense-category-delete'
            ],
            'office-income-category'=>[
                'office-income-category-manage',
                'office-income-category-add',
                'office-income-category-edit',
                'office-income-category-delete'
            ],
            'customer'=>[
                'customer-manage',
                'customer-add',
                'customer-show',
                'customer-edit',
                'customer-delete'
            ],
            'supplier'=>[
                'supplier-manage',
                'supplier-add',
                'supplier-edit',
                'supplier-delete'
            ],
            'store'=>[
                'store-manage',
                'store-add',
                'store-edit',
                'store-delete'
            ],
            'factory'=>[
                'factory-manage',
                'factory-add',
                'factory-edit',
                'factory-delete'
            ],
            'collection'=>[
                'collection-manage',
                'collection-add',
                'collection-show',
                'collection-delete',
            ],
            'payment'=>[
                'payment-manage',
                'payment-add',
                'payment-show',
                'payment-delete',
            ],
            'deposit'=>[
                'deposit-manage',
                'deposit-add',
                'deposit-show',
                'deposit-delete',
            ],
            'withdraw'=>[
                'withdraw-manage',
                'withdraw-add',
                'withdraw-show',
                'withdraw-delete',
            ],
            'expense'=>[
                'expense-manage',
                'expense-add',
                'expense-show',
                'expense-delete',
            ],
            'expense-report'=>[
                'expense-report-manage',
            ],
            'income'=>[
                'income-manage',
                'income-add',
                'income-show',
                'income-delete',
            ],
            'income-report'=>[
                'income-report-manage',
            ],
            'cashbook'=>[
                'cashbook-manage',
                'cashbook-previous-add',
            ],
            'author-ledger-book'=>[
                'author-ledger-book-manage',
                'author-ledger-book-show-all',
                'author-ledger-book-show-by-date',
            ],
            'main-account'=>[
                'main-account-manage',
            ],
            'bank-statement'=>[
                'bank-statement-manage',
                'bank-statement-previous-add',
            ],
            'bulk-name'=>[
                'bulk-name-manage',
                'bulk-name-add',
                'bulk-name-edit',
                'bulk-name-delete'
            ],
            'bulk-purchase'=>[
                'bulk-purchase-manage',
                'bulk-purchase-purchase',
                'bulk-purchase-show',
                'bulk-purchase-all-challan',
                'bulk-purchase-all-challan-by-date',
            ],
            'bulk-sales'=>[
                'bulk-sales-manage',
                'bulk-sales-sales',
                'bulk-sales-show',
                'bulk-sales-all-challan',
                'bulk-sales-all-challan-by-date',
            ],
            'bulk-stock'=>[
                'bulk-stock-manage',
                'bulk-stock-add',
                'bulk-stock-edit',
                'bulk-stock-stock-close',
            ],
            'send-to-repack-unit'=>[
                'send-to-repack-unit-manage',
                'send-to-repack-unit-send',
                'send-to-repack-unit-show',
                'send-to-repack-unit-accept',
                'send-to-repack-unit-reject',
            ],
            'purchase-ledger-book'=>[
                'purchase-ledger-book-manage',
                'purchase-ledger-book-show-all',
                'purchase-ledger-book-show-by-date',
                'purchase-ledger-book-all-ledger-book',
            ],
            'bulk-report'=>[
                'bulk-report-manage',
                'bulk-report-sales',
                'bulk-report-purchase',
                'bulk-report-send-to-repack-unit',
                'bulk-report-send-sales-&-repack-unit-challan',
            ],
            'repack-unit-qa/qc'=>[
                'repack-unit-qa/qc-manage',
                'repack-unit-qa/qc-show',
                'repack-unit-qa/qc-accept-or-reject',
            ],
            'repack-unit-production'=>[
                'repack-unit-production-manage',
                'repack-unit-production-ongoing',
                'repack-unit-production-complete',
                'repack-unit-production-send-to-store',
                'repack-unit-production-show',
            ],
            'repack-unit-production-report'=>[
                'repack-unit-production-report-manage',
            ],
            'store-product'=>[
                'store-product-manage',
                'store-product-add',
                'store-product-edit',
                'store-product-delete',
            ],
            'store-qa/qc'=>[
                'store-qa/qc-manage',
                'store-qa/qc-show',
                'store-qa/qc-accept-or-reject',
            ],
            'store-stock'=>[
                'store-stock-manage',
                'store-stock-add',
                'store-stock-edit',
                'store-stock-stock-close',
            ],
            'sales-sample'=>[
                'sales-sample-manage',
                'sales-sample-sample',
                'sales-sample-show',
                'sales-sample-challan',
                'sales-sample-invoice',
            ],
            'sales-sales'=>[
                'sales-sales-manage',
                'sales-sales-sales',
                'sales-sales-show',
                'sales-sales-reinvoice',
                'sales-sales-cancel-invoice',
                'sales-sales-all-challan-and-invoice',
                'sales-sales-all-challan-and-invoice-by-date',
                'sales-sales-challan',
                'sales-sales-invoice',
            ],
            'sales-return'=>[
                'sales-return-manage',
                'sales-return-return',
                'sales-return-show',
                'sales-return-all-invoice',
                'sales-return-all-invoice-by-date',
                'sales-return-invoice',
            ],
            'sales-ledger-book'=>[
                'sales-ledger-book-manage',
                'sales-ledger-book-edit',
                'sales-ledger-book-show-all',
                'sales-ledger-book-show-by-date',
                'sales-ledger-book-all-ledger-book',
            ],
            'sales-report'=>[
                'sales-report-manage',
            ],
            'sales-return-report'=>[
                'sales-return-report-manage',
            ],
            'sample-report'=>[
                'sample-report-manage',
            ],
            'production-report'=>[
                'production-report-manage',
            ],
            'employee-report'=>[
                'employee-report-manage',
                'employee-report-show',
            ],
            'customer-report'=>[
                'customer-report-manage',
            ],
            'trash-collection'=>[
                'trash-collection',
            ],

        ];
        foreach ($pers as $per => $val) {
            foreach ($val as $name) {
                Permission::create([
                    'module'        => $per,
                    'name'          => $name,
                    'removable'     => 0,
                ]);
            }
        }

        $superadmin = Role::create(['name' => 'superadmin','removable'=> 0]);
        $admin      = Role::create(['name' => 'admin','removable'=> 0]);
        $admin->givePermissionTo(Permission::all());
        $accountant = Role::create(['name' => 'accountant','removable'=> 0]);
        $employee   = Role::create(['name' => 'employee','removable'=> 0]);
    }
}
